- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Create cattle-system namespace
  command: kubectl create namespace cattle-system
  ignore_errors: yes

- name: Add Rancher Helm repo
  command: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest

- name: Update Helm repos
  command: helm repo update

- name: Install cert-manager CRDs
  command: |
    kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml

- name: Install cert-manager
  command: |
    helm upgrade --install cert-manager jetstack/cert-manager       --namespace cert-manager       --create-namespace       --version v1.14.4

- name: Install Rancher with Helm
  command: |
    helm upgrade --install rancher rancher-latest/rancher       --namespace cattle-system       --set hostname=rancher.yourdomain.com       --set replicas=1       --set bootstrapPassword=admin
