- name: Initialize Kubernetes Master
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output
  args:
    creates: /etc/kubernetes/admin.conf

- name: Save join command
  shell: |
    kubeadm token create --print-join-command > /joincluster.sh
  args:
    executable: /bin/bash

- name: Copy kubeconfig to regular user
  become_user: "{{ ansible_user }}"
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Calico network plugin
  become_user: "{{ ansible_user }}"
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
